
import azure from './azure.png'
import bootstrap from './bootstrap.jpg'
import firebase from './firebase.jpg'
import git from './git.jpg'
import github from './github.png'
import java from './java.png'
import javascript from './javascript.jpg'
import mysql from './mysql.png'
import node from './node.jpg'
import office from './office.jpg'
import php from './php.jpg'
import postgre from './postgre.png'
import python from './python.jpg'
import react from './react.jpg'
import symfony from './symfony.jpg'
import tailwind from './tailwind.png'
import typescript from './typescript.png'
import wordpress from './wordpress.png'
// import tailwind from './tailwind.jpg'

export {azure, bootstrap, firebase, git, github, java, javascript, mysql, node, office, php, postgre, python, react, symfony, tailwind, typescript, wordpress}
